### ISSUE TITLE
Github Reporting

### ISSUE THREAD

**Issue by phg49389** [betheluniversity/tinker#102]
(This issue was moved from Cascade/Issues because Tinker is where the code for it is being written)

We would like to find a GitHub API that can help us generate useful reporting. Hopefully we can find a Python API. Some examples include:
-     List all users and the number of issues/comments/etc. associated with them for a given date range.
-     Various averages on issues. i.e. average time an issue was open
-     And anything other report that we can generate that provides cool or useful reporting.

**Comment by c-schwarze** [comment]
We moved away from needing this, as both the Dashboard project has been put on hold AND we don't use github for as many things as we used to.
