### ISSUE TITLE
Tinker Design changes

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#108]
We are looking to modify some of the design of tinker. Update the nav/title so it doesn't overlap awkwardly. Change the <small> tags we currently use for field descriptions to something larger. Update the default font to bethel fonts. And there are plenty of other modifications.

@josiahtillman want to get started on this when you have a chance?

**Comment by e-jameson** [comment]
closing as this is going to be worked into our big summer project.
