### ISSUE TITLE
Tinker Event Editing

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/tinker#122]
Received this from Ann Gannon (FP job 17182)

---------- Forwarded message ----------
From: Ann Gannon <agannon@bethel.edu>
Date: Wed, Mar 23, 2016 at 10:30 AM
Subject: Re: Change April 5 Triptych: A Reading to April 21
To: Jan Jessup <j-jessup@bethel.edu>

Jan,
When you have a chance...

When I try to go in to edit an accepted event, the form allows me to change
the date, but the time drop down menu does not appear and the time reverts
to 12 am.

The form also looks like it deletes some of the other fields like special
instructions.

I don't know if these things can be changed in your system, but if editing
is an option - it seems like I should be able to edit it all and also trust
that all the fields don't have to be rewritten.

**Comment by c-schwarze** [comment]
Fixed.

**Comment by c-schwarze** [comment]
wrong issue --ignore that commit
