### ISSUE TITLE
HTML in e-announcement

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/tinker#126]
From FP job 17223:
Entered on 03/30/2016 at 16:31:09 CDT (GMT-0500) by Jan Jessup:
Hi team,
I submitted a couple of e-anns today. When I went in to edit them, several
odd characters [ ] had been inserted in various places between words
in the content with no apparent pattern. I typed in all content from
scratch (no copying and pasting). 
![image_20160330163109_33387](https://cloud.githubusercontent.com/assets/6526079/14178100/c80bdc98-f71e-11e5-92cf-9dd84006d26b.png)

**Comment by c-schwarze** [comment]
I don't see the error on the e-announcement in cascade or in the tinker view. I also copied the text and can't replicate it :( 

I will try to spend some time doing research to figure out why this is an issue for Jan

**Comment by c-schwarze** [comment]
Fixed!

**Comment by c-schwarze** [comment]
Actually, reopening. @annmarieven could you respond back to Jan?

This issue shouldn't happen again, but it still exists on any current e-announcement
