### ISSUE TITLE
bethelnet redirect

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/tinker#135]
Can you redirect:

https://bethelnet.bethel.edu/gs-students/documents/forms/incomplete
to
https://bethelnet.bethel.edu/gs-students/forms/

Thanks!

**Comment by emily-johnson** [comment]
and also:

https://bethelnet.bethel.edu/caps-students/documents/forms/incomplete
to
https://bethelnet.bethel.edu/caps-students/forms/

**Comment by e-jameson** [comment]
these are both done.
