### ISSUE TITLE
Library locations

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/tinker#137]
The Cascade field/Tinker dropdown for '[on campus location](https://tinker.bethel.edu/event/add)'  should include these 3 options:
Library - Seminary San Diego
Library - Seminary St. Paul
Library - University

They should be listed on the actual event page as their official names:
Bethel University Library
Bethel Seminary Library St. Paul
Bethel Seminary Library San Diego 

Thanks!

**Comment by emily-johnson** [comment]
Now I'm not seeing it on any events

**Comment by c-schwarze** [comment]
Is this comment supposed to be in another github issue?

**Comment by emily-johnson** [comment]
Oh oops, yeah haha

**Comment by c-schwarze** [comment]
Wow. This slipped through the cracks. Sorry it took so long -_-

You should be able to just update the fields in Cascade via the block maps-directions block: https://cms.bethel.edu/entity/open.act?id=ba1355ea8c586513100ee2a725b9ebea&type=block&

**Comment by c-schwarze** [comment]
@emily-johnson is this finished?

**Comment by c-schwarze** [comment]
closing. we are changing the values of the field to what brooke jameson wants.
