### ISSUE TITLE
Ticketing - Remove Wufoo Hash Code & add URL

### ISSUE THREAD

**Issue by kuhste** [betheluniversity/tinker#143]
Can we update the "New Event" portion of tinker. Under "Does your event require registration or payment?" can the "Ticketing" heading option request a URL instead of a wufoo hash code?

We will fill them in with University Tickets Urls, such as: http://betheltickets.universitytickets.com/user_pages/event.asp?id=198&cid=30

Let me know if you need anything else.

sk.

**Comment by c-schwarze** [comment]
Done
