### ISSUE TITLE
Side Navigation permissions issues

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#197]
Currently, we have no way to nicely manage permissions of the admin menus (since its built in each module's before_request, in the hide/show of the 'Admin' menu, and hide/show for each link).

**Comment by bak45247** [comment]
for this 'fix' are we looking to have one 'admin-permissions' file that all the before_request methods would call?

**Comment by e-jameson** [comment]
I'm guessing Caleb didn't have something in mind, so we can kind of be creative here. One thought is, what if there was a parent function in `TinkerController` file and the `before_request` for each module passed some info in, like what types of groups or people are allowed access. And then all the logic is in the function in `TinkerController`. That would consolidate logic and the modules would only need to specify whats allowed.

Just brainstorming, I also don't 100% remember how it currently works. But see if that gets you on the right track.

**Comment by bak45247** [comment]
i actually just made a new .py file containing basically all of the permissions from the before_requests that each module calls

**Comment by bak45247** [comment]
i moved the contents of the new .py file over to the tinker controller
