### ISSUE TITLE
Favicon.ico route failing

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#199]
We keep getting sentry errors from people going to tinker.bethel.edu/favicon.ico. We should just make a route for it so the error stops getting created.

**Comment by c-schwarze** [comment]
It might also be wise to look into how other flask applications deal with this?

**Comment by phg49389** [comment]
I think Boston fixed it on this commit: https://github.com/betheluniversity/tinker/commit/fb4fc3480cf62e61aa2dc9c9870416f587d728be

**Comment by c-schwarze** [comment]
yeah closing
