### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/tinker#226]
Redirects/rules found while closing the legacy systems ([audit](https://docs.google.com/spreadsheets/d/1S7QhvcAy1aAvzcLf_-QgGRzsbhFftFQwsY2sLUxV1O8/edit#gid=34747613))

- [x] /bsa/exchange
to 
https://book-exchange.bethel.edu/

- [x] graduate-back/ _(I'm not sure why it was called this?)_
to
https://www.bethel.edu/graduate/

**Comment by emily-johnson** [comment]
- [ ] gs.bethel.edu/academics/graduate-testing/mat-flyer.pdf
to
https://www.bethel.edu/graduate/academics/graduate-testing/

**Comment by emily-johnson** [comment]
- [ ] bsa.bethel.edu/contact-us
to
https://www.bethel.edu/undergrad/bsg/contact/

- [ ] bsa.bethel.edu/contact-us
to
https://www.bethel.edu/undergrad/bsg/

**Comment by e-jameson** [comment]
These are all done. The BSA ones are already being redirected to WWW, so the redirects can be done in Tinker.

**Comment by kathrynmagnuson** [comment]
@e-jameson can you redirect these?

- [ ] https://bethelnet.bethel.edu/bsoe-faculty/
www.bethel.edu/seminary

- [ ] https://bethelnet.bethel.edu/bsoe-faculty/booklist
www.bethel.edu/seminary

- [ ] https://bethelnet.bethel.edu/bsoe-faculty/locations
www.bethel.edu/seminary

**Comment by e-jameson** [comment]
@kathrynmagnuson the first three are done, the 4th you should be able to do in Tinker.

**Comment by emily-johnson** [comment]
Oops, that was mine, didn't realize the rule has gotten it before I copied it in here. Thanks!

**Comment by kathrynmagnuson** [comment]
@e-jameson can you do a rule for https://bethelnet.bethel.edu/business-office/ to https://www.bethel.edu/business-office/ ? And then we can do the individual ones in tinker.

**Comment by e-jameson** [comment]
yep, done

**Comment by emily-johnson** [comment]
URLs for the **redirects** that we discussed:

- [ ] bsa.bethel.edu/sa/
https://www.bethel.edu/undergrad/bsg/departments/student-activities/

- [ ] bsa.bethel.edu/contact-us
https://www.bethel.edu/undergrad/bsg/contact/

- [ ] bsa.bethel.edu/marketing/
https://www.bethel.edu/undergrad/bsg/departments/communications-marketing/

- [ ] bsa.bethel.edu/leadership/
https://www.bethel.edu/undergrad/bsg/departments/leadership/

- [ ] bsa.bethel.edu/underground/
https://www.bethel.edu/events/arts/venues/underground

- [ ] bsa.bethel.edu/getinvolved/
https://www.bethel.edu/undergrad/bsg/join/

- [ ] bsa.bethel.edu/senate
https://www.bethel.edu/undergrad/bsg/student-senate/

**Comment by emily-johnson** [comment]
Rules:
- [ ] http://caps.bethel.edu/seminars/
https://www.bethel.edu/adult-undergrad/

**Comment by kathrynmagnuson** [comment]
@e-jameson 
- [ ] rule needed for https://bethelnet.bethel.edu/facilities-mgmt/ to https://www.bethel.edu/facilities/

**Comment by kathrynmagnuson** [comment]
- [ ] https://bethelnet.bethel.edu/academic-affairs/ to https://www.bethel.edu/undergrad/academic-affairs/

**Comment by e-jameson** [comment]
both are done!

**Comment by emily-johnson** [comment]
@e-jameson 
Rule:
cas.bethel.edu/actitivies/ to
https://www.bethel.edu/undergrad/

@emily-johnson
Tinker redirects:
undergrad/resources to
https://www.bethel.edu/undergrad/

**Comment by emily-johnson** [comment]
##cas.bethel.edu redirects
@e-jameson
Pages shouldn’t keep the path for:
- [ ] /dept/stu-org
https://www.bethel.edu/undergrad/bsg/clubs-organizations/academic
- [ ] /dept/anthropology
https://www.bethel.edu/undergrad/academics/anthropology-sociology-reconciliation/
- [ ] /dept/biblical-theological
https://www.bethel.edu/undergrad/academics/biblical-theological/
- [ ] /dept/biochem-molbio
https://www.bethel.edu/undergrad/academics/biology/majors-minors/biochemistry-molecular
- [ ] /dept/biology
https://www.bethel.edu/undergrad/academics/biology
- [ ] 

Individual redirects (aesc isn't getting a rule)
- [ ] /dept/aesc/Science%20Tutor%20Lab
https://www.bethel.edu/undergrad/academics/support/science
- [ ] /dept/aesc/toc  (table of contents, not sure if we need to do this)
https://www.bethel.edu/undergrad/academics/support/
- [ ] /dept/aesc/Business%20Lab
https://www.bethel.edu/undergrad/academics/support/business
- [ ] /dept/aesc/academic-integrity/
https://www.bethel.edu/undergrad/academics/support/
- [ ] /dept/aesc/presenter/
https://www.bethel.edu/undergrad/academics/support/
- [ ] 
##Tinker redirects
@emily-johnson

**Comment by kathrynmagnuson** [comment]
@e-jameson rule for:
 

- [ ] https://bethelnet.bethel.edu/bsoe-faculty/ to https://www.bethel.edu/seminary/ (https://bethelnet.bethel.edu/bsoe-faculty/ redirects but none of the other pages in the folder do)

**Comment by kathrynmagnuson** [comment]
@e-jameson rule for:

- [ ] https://bethelnet.bethel.edu/bsspstudent/index to https://www.bethel.edu/seminary/

**Comment by kathrynmagnuson** [comment]
@e-jameson rule for:

- [ ] https://bethelnet.bethel.edu/purchasing/ to https://www.bethel.edu/purchasing/

**Comment by kathrynmagnuson** [comment]
# bethelnet.bethel.edu redirects: 
@e-jameson pages shouldn't keep path for:

- [ ] ureg/bssd/calendars to https://www.bethel.edu/seminary/academics/calendars/san-diego/

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirects: 
@e-jameson pages shouldn't keep path for:

- [ ] ureg/bssp/graduation to https://www.bethel.edu/registrar/graduation/

- [ ] ureg/bssp/Calendars to https://www.bethel.edu/seminary/academics/calendars/st-paul/

- [ ] ureg/bssp/guide-sheets to https://www.bethel.edu/registrar/registration/seminary/2016-2017/

- [ ] ureg/bssp/schedules/courses to https://www.bethel.edu/registrar/registration/seminary/

- [ ] ureg/bssp/schedules/refund to https://confluence.bethel.edu/x/FgGC

**Comment by e-jameson** [comment]
these are all done

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirects:
@e-jameson page shouldn't keep path
- [ ] ureg/bssp/banner to https://www.bethel.edu/registrar/faculty-staff/registration-instructions

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirects:
@e-jameson pages shouldn't keep path:

- [ ] bsoe-faculty to https://www.bethel.edu/seminary/

- [ ] caps-faculty to https://www.bethel.edu/adult-undergrad/

- [ ] comm-marketing to https://www.bethel.edu/marketing/

**Comment by kathrynmagnuson** [comment]
redirect rule for:

- [ ] https://bethelnet.bethel.edu/security-safety/security/Clery_Act/index to https://www.bethel.edu/security-safety/policies-statistics

**Comment by kathrynmagnuson** [comment]
@e-jameson redirect rule for: 

- [ ] https://bethelnet.bethel.edu/semprovost/ to https://www.bethel.edu/seminary/

**Comment by kathrynmagnuson** [comment]
@e-jameson redirect
 

- [ ] https://bethelnet.bethel.edu/equality-ride/index

 to https://www.bethel.edu/

**Comment by kathrynmagnuson** [comment]
@e-jameson ghost pages to be closed in silva

- [ ] http://zope1.its.bethel.edu:8080/silva/bethelnet/ureg/bssp/eval_index

- [ ] http://zope1.its.bethel.edu:8080/silva/bethelnet/ureg/bssp/acp

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirect rule: 

@e-jameson pages shouldn't keep path
- [ ] ureg/bssp/forms/ to https://www.bethel.edu/registrar/forms/

**Comment by kathrynmagnuson** [comment]
- [ ] purchasing/docs to https://www.bethel.edu/purchasing/

**Comment by kathrynmagnuson** [comment]
@e-jameson redirect for:

- [ ] bethelnet.bethel.edu/a-z to https://www.bethel.edu/offices

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirect rule:
@e-jameson pages shouldn't follow path for:

- [ ] ureg/bssp/schedules to https://www.bethel.edu/registrar/important-dates-schedules/cohort-schedules

**Comment by kathrynmagnuson** [comment]
- [ ] /ureg/inmin/forms to https://www.bethel.edu/registrar/forms/

- [ ] ureg/inmin/registration to https://www.bethel.edu/registrar/registration/seminary/

- [ ] ureg/inmin/schedules to https://www.bethel.edu/registrar/registration/seminary/

- [ ] ureg/inmin/graduation to https://www.bethel.edu/seminary/

- [ ] ureg/inmin/guide-sheets to https://www.bethel.edu/registrar/registration/seminary/2016-2017/

- [ ] ureg/inmin/calendars to https://www.bethel.edu/seminary/academics/calendars/

**Comment by kathrynmagnuson** [comment]
ghost pages - please close! :) 

- [ ] http://zope1.its.bethel.edu:8080/silva/bethelnet/ureg/inmin/index/edit/tab_edit

- [ ] http://zope1.its.bethel.edu:8080/silva/bethelnet/ureg/inmin/calendars/edit/tab_edit

- [ ] http://zope1.its.bethel.edu:8080/silva/bethelnet/ureg/inmin/banner/edit/tab_edit

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirect rule:
pages shouldn't keep path for:
- [ ] caps-students to https://www.bethel.edu/adult-undergrad/

**Comment by e-jameson** [comment]
@kathrynmagnuson these are all done. This issue is getting pretty long so I'm closing it. Let's start a new one for new rules.

**Comment by kathrynmagnuson** [comment]
Hey @e-jameson could you take a look at the 3 redirects I un-checked? They don't seem to be redirecting. Thanks!

**Comment by e-jameson** [comment]
Yep -- 

- ureg/inmin/forms to https://www.bethel.edu/registrar/forms/
 and 
- ureg/inmin/registration to https://www.bethel.edu/registrar/registration/seminary/

are redirecting for me. Try clearing your cache or an incognito window.

- caps-students to https://www.bethel.edu/adult-undergrad/

should now be working

**Comment by kathrynmagnuson** [comment]
@e-jameson hmmm ok, for me /ureg/inmin/forms goes to /registrar/inmin/forms (keeping the 'inmin' when it shouldn't & giving a 404 (Same with the /registration one). But if it's working for you then it's probably my cache :) The caps-students redirect is working for me though

**Comment by e-jameson** [comment]
I just confirmed it an Incognito window and they seem to be working correctly

**Comment by kathrynmagnuson** [comment]
@e-jameson Are the redirects on this page for the aesc working for you? They aren't for Em & me.

**Comment by e-jameson** [comment]
They are working for me. Can you double check @kathrynmagnuson @emily-johnson

**Comment by kathrynmagnuson** [comment]
@e-jameson the aesc redirects are all going to bethel.edu now for me (instead of the link under each one)

**Comment by e-jameson** [comment]
I fixed something and confirmed they all work except for the ones with the %20 (spaces). We are going to just leave those going to the homepage as Apache is weird about spaces and URLs.
