### ISSUE TITLE
Events names

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#231]
It appears that the titles of some images are not being created properly through tinker. (notice the space before the image name)
![screen shot 2017-05-31 at 10 51 23 am](https://cloud.githubusercontent.com/assets/7849657/26641566/9df25654-45f0-11e7-8b67-facbfc3d4203.png)

**Comment by bak45247** [comment]
This bug was caused by an unnecessary space before his last name in the faculty bios form.

**Comment by e-jameson** [comment]
Can we update the controller to strip leading spaces before fields?

**Comment by bak45247** [comment]
yes

**Comment by c-schwarze** [comment]
@tim-heck want to take a look at this? Run some tests and see if you can reproduce it

**Comment by c-schwarze** [comment]
I believe Tim Heck fixed this before he left. I forgot to be closed.
