### ISSUE TITLE
Individual Page Redirects

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/tinker#238]
## redirects for cas.bethel.edu

- [x] /dept/aesc/Science%20Tutor%20Lab
https://www.bethel.edu/undergrad/academics/support/science

- [x] /dept/aesc/Business%20Lab
https://www.bethel.edu/undergrad/academics/support/business

- [x] /dept/aesc/toc
https://www.bethel.edu/undergrad/academics/support/

- [x] /dept/aesc/copy_of_handouts
https://www.bethel.edu/undergrad/academics/support/study-skills/

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/aesc/schedule/index 
https://www.bethel.edu/undergrad/academics/support/meet-counselor

**Comment by e-jameson** [comment]
These are done!

**Comment by kathrynmagnuson** [comment]
- [ ] bethelnet.bethel.edu/ureg/cas/faculty/Course_Progress_Report.pdf
 https://beacon-cas.bethel.edu/

**Comment by kathrynmagnuson** [comment]
- [ ] cas.bethel.edu/dept/dept/music/adjunct
https://www.bethel.edu/undergrad/academics/music/faculty

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/mw-languages/ppt-accents
https://www.bethel.edu/undergrad/academics/world-languages/language-placement/typing-foreign-accents.pdf

- [ ] /dept/mw-languages/word-accent
https://www.bethel.edu/undergrad/academics/world-languages/language-placement/typing-foreign-accents.pdf

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/philosophy/staff-shady
https://www.bethel.edu/academics/faculty/shady-sara

- [ ] /dept/philosophy/staff-yim
https://www.bethel.edu/academics/faculty/yim-daniel

- [ ] /dept/philosophy/staff-peffley
https://www.bethel.edu/academics/faculty/peffley-carrie

- [ ] /dept/philosophy/staff-reasoner
https://www.bethel.edu/academics/faculty/reasoner-paul

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/political-science/vangeest
https://www.bethel.edu/academics/faculty/vangeest-fred

- [ ] /dept/political-science/cmoore
https://www.bethel.edu/academics/faculty/moore-christopher

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/theatre/faculty
https://www.bethel.edu/undergrad/academics/theatre/faculty

- [ ] /dept/theatre/archive
https://www.bethel.edu/undergrad/academics/theatre/past-productions/

**Comment by kathrynmagnuson** [comment]
@e-jameson here's the next batch of redirects! We're getting close to being done! :)

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu:

- [ ] /human-resources/current-employees/training
https://www.bethel.edu/human-resources/employee-resources/current-employee-toolkit/

- [ ] /human-resources/current-employees/employee-leadership-institute
https://www.bethel.edu/human-resources/employee-resources/current-employee-toolkit/

**Comment by kathrynmagnuson** [comment]
- [ ] /hr/benefits-announcements
https://www.bethel.edu/human-resources/

- [ ] /hr/United-Way
https://www.bethel.edu/human-resources/

- [ ] /hr/technical-training-hr
https://www.bethel.edu/human-resources/

- [ ] /hr/training-recordings
https://www.bethel.edu/human-resources/

- [ ] /hr/training-resources
https://www.bethel.edu/human-resources/

**Comment by e-jameson** [comment]
these are done. lets start a new issue
