### ISSUE TITLE
Redirect Rules

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/tinker#239]
## batch redirect rules for cas.bethel.edu

- [x] /dept/comm
https://www.bethel.edu/undergrad/academics/communication/

- [x] /dept/environmental-studies
https://www.bethel.edu/undergrad/academics/environmental-studies/

- [x] /dept/history
https://www.bethel.edu/undergrad/academics/history/

- [x] /dept/honors
https://www.bethel.edu/undergrad/academics/honors/

@e-jameson could you check if these 4 are keeping the path or not? They shouldn't be (should go to the main page of the corresponding department). Thanks!

**Comment by kathrynmagnuson** [comment]
pages shouldn't keep path:
- [ ] explore-connect.bethel.edu
https://www.bethel.edu/

**Comment by kathrynmagnuson** [comment]
## cas.bethel.edu 
pages shouldn't keep path
- [ ] /dept/nehtocqueville/ 
https://www.bethel.edu/

**Comment by e-jameson** [comment]
These are done. explore-connect.bethel.edu doesn't exist so I didn't do anything with it.

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirects:

- [ ] /caps-faculty
https://www.bethel.edu/graduate/

- [ ] /caps-students
https://www.bethel.edu/graduate/

- [ ] /cas-faculty
https://www.bethel.edu/undergrad/

**Comment by kathrynmagnuson** [comment]
- [ ] /gs-students
https://www.bethel.edu/graduate/

- [ ] /gs-faculty
https://www.bethel.edu/graduate/

**Comment by kathrynmagnuson** [comment]
- [ ] /semfac
https://www.bethel.edu/seminary/

**Comment by kathrynmagnuson** [comment]
- [ ] /student-life
https://www.bethel.edu/undergrad/student-life/

**Comment by kathrynmagnuson** [comment]
- [ ] /semprovost
https://www.bethel.edu/seminary/

**Comment by kathrynmagnuson** [comment]
@e-jameson above are a few more redirects. Thanks!

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirects:

- [ ] /faculty 
https://www.bethel.edu/

**Comment by kathrynmagnuson** [comment]
@e-jameson there is currently a rule:
bethelnet.bethel.edu/academic-affairs to bethel.edu/undergrad/academic-affairs but we need the following page to _not_ redirect:

- [ ] https://bethelnet.bethel.edu/academic-affairs/caps-gs/coursedevelopment/addendum

**Comment by e-jameson** [comment]
This is done. People will need to clear their cache before it will work again

**Comment by kathrynmagnuson** [comment]
@e-jameson can you put these redirects in after any that are already there? (some pages are already redirecting to various places and that's fine, we just want what isn't redirecting to go to the home pages) If you need clarification or if that's not possible let me know - thanks!
- [ ] seminary.bethel.edu
https://www.bethel.edu/seminary/

- [ ] gs.bethel.edu
https://www.bethel.edu/graduate/

**Comment by e-jameson** [comment]
The rest of these are done too. Lets start a new one again :)
