### ISSUE TITLE
Redirect Rules

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/tinker#243]
## cas.bethel.edu redirects
pages shouldn't keep path

- [x] /dept/physics
https://www.bethel.edu/undergrad/academics/physics/

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/music/adjunct
https://www.bethel.edu/undergrad/academics/music/
*there is one page that needs a specific redirect (see individual page redirects issue), but the rest should go here without keeping the path, if that's possible.

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/political-science
https://www.bethel.edu/undergrad/academics/political-science/ 
(except for 2 pages in individual page redirects issue that need to go to specific pages)

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/religious-studies
https://www.bethel.edu/undergrad/academics/biblical-theological/

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/psychology/MA
https://www.bethel.edu/graduate/academics/counseling/

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/science-ed
https://www.bethel.edu/undergrad/academics/biology/majors-minors/life-science-education

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/theatre
https://www.bethel.edu/undergrad/academics/theatre/
(except for 2 pages in "individual page redirects" issue that need to go to specific pages)

**Comment by kathrynmagnuson** [comment]
@e-jameson here are a few more rules

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirects:

- [ ] /hr/forms
https://www.bethel.edu/human-resources/forms/

- [ ] /hr/recognition
https://www.bethel.edu/human-resources/recognition/

- [ ] /hr/training
https://www.bethel.edu/human-resources/

- [ ] /hr/supervisor-toolkit
https://www.bethel.edu/human-resources/employee-resources/supervisor-toolkit/

**Comment by kathrynmagnuson** [comment]
- [ ] /hr/your-hr-news
https://www.bethel.edu/human-resources/

- [ ] /hr/opportunities
https://www.bethel.edu/human-resources/

**Comment by kathrynmagnuson** [comment]
## cas.bethel.edu redirects:

- [ ] /dept/math-cs
https://www.bethel.edu/undergrad/academics/math-cs/

**Comment by e-jameson** [comment]
these are done

**Comment by kathrynmagnuson** [comment]
## www.bethel.edu redirects:

- [ ] /campus-store
http://bookstore.bethel.edu

**Comment by kathrynmagnuson** [comment]
## www.bethel.edu redirects:

- [ ] /publications-archive/bethel-investor
https://www.bethel.edu/news/publications/bethel-investor/

- [ ] /publications-archive/parent
https://www.bethel.edu/news/publications/bethel-parent/

- [ ] /publications-archive/magazine
https://www.bethel.edu/news/publications/bethel-magazine/

Note: I think there is currently a rule for /publications-archive/ to https://www.bethel.edu/news/publications/ but these folders should go to the more specific folders listed. Thanks!

**Comment by kathrynmagnuson** [comment]
## cas.bethel.edu redirects

- [ ] /dept/comm/forensics
https://www.bethel.edu/undergrad/academics/communication/forensics/

- [ ] /dept/comm/europe
https://www.bethel.edu/undergrad/academics/communication/europe-term

After these redirects, the rest should go to the main comm page without keeping the path:
- [ ] /dept/comm
https://www.bethel.edu/undergrad/academics/communication/

**Comment by kathrynmagnuson** [comment]
## bethelnet.bethel.edu redirects

(pages shouldn't follow path)
- [ ] /hr/news/
https://www.bethel.edu/human-resources/news/hr-news-archive

**Comment by kathrynmagnuson** [comment]
## www.bethel.edu redirect
batch redirect/don't follow path for
- [ ] /self-study
https://www.bethel.edu/

**Comment by kathrynmagnuson** [comment]
## www.business-office folder redirects
batch redirect/pages shouldn't keep path
- [ ] /cas
https://www.bethel.edu/business-office/payment-plans/undergrad
- [ ] /caps
https://www.bethel.edu/business-office/payment-plans/graduate-adult-undergrad
- [ ] /gs
https://www.bethel.edu/business-office/payment-plans/graduate-adult-undergrad
- [ ] /seminary
https://www.bethel.edu/business-office/payment-plans/seminary
- [ ] /images
https://www.bethel.edu/
- [ ] /shared
https://www.bethel.edu/
- [ ] /old
https://www.bethel.edu/

**Comment by kathrynmagnuson** [comment]
## www.bethel.edu redirect
pages shouldn't keep path
- [ ] /bethel-news
https://www.bethel.edu/news/

**Comment by e-jameson** [comment]
These are all done, aside from /dept/comm/forensics and /dept/comm/. 

I'm going to close this issue. Go ahead and add those to a new issue when they are ready to be created.
