### ISSUE TITLE
Individual Page Redirects

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/tinker#244]
## cas.bethel.edu redirects

- [x] /dept/history/fac/g-carlson
https://www.bethel.edu/undergrad/academics/history/faculty

- [ ] /dept/history/fac/k-cragg
https://www.bethel.edu/undergrad/academics/history/faculty

- [ ] /dept/history/fac/c-gehrz
https://www.bethel.edu/academics/faculty/gehrz-christopher

- [ ] /dept/history/fac/d-magnuson
https://www.bethel.edu/academics/faculty/magnuson-diana

- [x] /dept/history/fac/r-rivera
https://www.bethel.edu/academics/faculty/rivera-ruben

- [x] /dept/history/fac/a-kooistra
https://www.bethel.edu/academics/faculty/kooistra-annemarie

- [x] /dept/history/fac/s-mulberry
https://www.bethel.edu/academics/faculty/mulberry-sam

- [x] /dept/history/fac/s-keillor
https://www.bethel.edu/undergrad/academics/history/faculty

- [x] /dept/history/fac/a-poppinga
https://www.bethel.edu/academics/faculty/poppinga-amy

- [x] /dept/history/fac/r-tshihamba
https://www.bethel.edu/undergrad/academics/history/faculty

- [x] /dept/history/fac/r-salo
https://www.bethel.edu/undergrad/academics/history/faculty

**Comment by kathrynmagnuson** [comment]
- [ ] /dept/comm/faculty/index
https://www.bethel.edu/undergrad/academics/communication/faculty

- [ ] /dept/comm/faculty/l-frazier
https://www.bethel.edu/academics/faculty/frazier-leta

- [ ] /dept/comm/faculty/m-dreher
https://www.bethel.edu/academics/faculty/dreher-michael

- [ ] /dept/comm/faculty/s-sochay
https://www.bethel.edu/academics/faculty/sochay-scott

- [ ] /dept/comm/faculty/p-kendall
https://www.bethel.edu/academics/faculty/kendall-peggy

- [ ] /dept/comm/faculty/a-guess
https://www.bethel.edu/academics/faculty/gess-andrew

- [ ] /dept/comm/faculty/s-pelham
https://www.bethel.edu/undergrad/academics/communication/faculty

- [ ] /dept/comm/faculty/n-brule
https://www.bethel.edu/academics/faculty/brule-nancy

- [ ] /dept/comm/faculty/p-frazier
https://www.bethel.edu/academics/faculty/frazier-phil

- [ ] /dept/comm/faculty/a-terry
https://www.bethel.edu/academics/faculty/terry-artie

- [ ] /dept/comm/faculty/k-mcannany
https://www.bethel.edu/undergrad/academics/communication/faculty

- [ ] /dept/comm/faculty/r-smith
https://www.bethel.edu/academics/faculty/smith-ripley

- [ ] /dept/comm/faculty/j-samens
https://www.bethel.edu/academics/faculty/samens-jessica

**Comment by e-jameson** [comment]
done

**Comment by c-schwarze** [comment]
@e-jameson where is this at?
