### ISSUE TITLE
Events (and e-annz)

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#250]
Brooke would like a feature for events where your last searched fields are saved the next time you search. 

I think we should be able to store this via cookies or even the session.

**Comment by c-schwarze** [comment]
This should be completed after #230 is completed

**Comment by c-schwarze** [comment]
#230 is finished. This can be done whenever.

**Comment by c-schwarze** [comment]
@bam95899, when you are in next (maybe february), this is something that you can work on after pagination.

**Comment by bam95899** [comment]
Completed in PR #346
