### ISSUE TITLE
Pagination needed for E-Announcements ALL

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/tinker#297]
When All E-Announcements are viewed they are all loaded to the page, which makes it a gigantic page that is very laggy. The view should be updated to have pages displaying only a certain number at a time.

**Comment by c-schwarze** [comment]
This might also be good for Events

**Comment by bam95899** [comment]
Finished in PR #334

**Comment by bam95899** [comment]
Finished in PR #334
