### ISSUE TITLE
Events can be submitted without end dates?

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#316]
It looks like someone submitted an event without an end date

https://sentry.io/bethel-university/tinker/issues/661665205/?referrer=slack

@j-jasik want to take a look at this next time you are in? I want to try to pass you more "random" requests/issues that come in.

**Comment by j-jasik** [comment]
Yeah I'll definitely take a look as soon as I can.

**Comment by j-jasik** [comment]
After looking into this error I was unable to replicate the conditions to make it happen. The error appears at a point in the code (get_year_folder_value in events_controller.py) when the end date should be a valid value, even if the user checks the box for "no end date". Further, the front end does not allow users to submit a new event with an empty end date field AND without checking the box for no end date. It's a mystery as to how the specific event caused this error.

**Comment by c-schwarze** [comment]
I think this one might have been a fluke. I'm going to close unless we see this again.
