### ISSUE TITLE
Give the help desk staff access to User Roles

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#320]
The Help Desk should be able to act as a user. I think this enable them to debug things a bit further, as none of them can even see the faculty bio sections. We should also protect the other areas of admin functionality from them, just in case they misclick or want to see what something does. Or something along those lines.

**Comment by bak45247** [comment]
What is the help-desk role called? 

It should be pretty simple, just placing that logic in the admin menu and then disallowing them to see anything but the user roles option
