### ISSUE TITLE
Deactivating Faculty Clear Cache

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#349]
Deactivating faculty has become an issue due to the faculty bio xml being cached for 5 minutes. We can't lose cacheing, due to the increase in time.

We should look into clearing the cache after a deactivate OR delete.

**Comment by bak45247** [comment]
We can use:

cache.clear()

after the activate/deactivate functions to immediately clear the cache

**Comment by bak45247** [comment]
We're actually not going to use cache.clear() as that will get rid of everything cached. Instead we'll use cache.delete_memoized() to delete the cache for only the faculty bios page. This way we won't have any loss on loading speeds for other pages due to the faculty bios methods

**Comment by c-schwarze** [comment]
@bam95899 where is this at? can this be closed?

**Comment by bam95899** [comment]
@bak45247 I think ya meant

**Comment by c-schwarze** [comment]
Yeah, @bak45247, where is this at?

**Comment by bak45247** [comment]
this was pulled

**Comment by bak45247** [comment]
https://github.com/betheluniversity/tinker/pull/363
