### ISSUE TITLE
Redirect Audit - Turn off altogether or run rarely

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#387]
At this point, the redirect audit is still sending blank emails the first day of the month.

However, I think that the audit might not be helpful to run every month anymore. The old redirects rarely are updated. We could consider having this run at larger intervals?

It might be helpful to consider fixing redirects as they are entered? We don't want it to be confusing, in the sense that the redirect changes on the user. However, almost every change we make does not change the redirect end destination, just the path to get there.

**Comment by bak45247** [comment]
we could have it run quarterly or biannually?

**Comment by c-schwarze** [comment]
Lets have this run 2-4 times a year. The first thing we will need to update is making sure we aren't sending emails if its blank.

**Comment by bam95899** [comment]
Fixed via puppet code. Closing.
