### ISSUE TITLE
Events - all day setting doesn't hide end date. Seems weird.

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#393]
This is an example on https://tinker.bethel.edu/events/edit/0cca88288c5865ef422d69cbe92944c4

![Screen Shot 2019-11-04 at 1 57 23 PM](https://user-images.githubusercontent.com/7849657/68153794-cc5ed180-ff0b-11e9-9427-640d6706eb8a.png)

**Comment by bam95899** [comment]
@c-schwarze currently when All Day is selected and No End Date is selected, and you unselect No End Date the End Date datepicker shows up again. Do we want that same behavior still or do we want it to still be hidden since All Day is still checked?

**Comment by c-schwarze** [comment]
not actually an issue - my bad.
