### ISSUE TITLE
Automatic description for faculty bios

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#41]
Can we have descriptions automatically pull for faculty bios?

'Meet [first name last name], [job title] of [first department name].'

**Comment by kelslundberg** [comment]
What if we dropped the program name and added Bethel instead...

"Meet Tim Hammer, Instructor of Biology at Bethel University"

It wouldn't be ideal for people who just have "professor" or whatever, but it should make sense logically.

Thoughts?

**Comment by annmarieven** [comment]
I think that's probably our only option :) Thanks for following up with this @kelslundberg.

So it will be 'Meet [first name last name], [job title] at Bethel University.'

**Comment by c-schwarze** [comment]
Updated.

**Comment by annmarieven** [comment]
Do we need to republish all bios for this to be implemented?

**Comment by e-jameson** [comment]
All bios would need to be re-submitted through tinker

**Comment by kelslundberg** [comment]
What does that entail...

**Comment by e-jameson** [comment]
For each Faculty Bio, get the Cascade ID (00b776998c586513100ee2a7c6e5e3f3) and go to

https://tinker.bethel.edu/faculty-bios/edit/<id>

Don't change anything just click submit.

**Comment by annmarieven** [comment]
We have to manually do that for all 200+ bios?

**Comment by e-jameson** [comment]
If you ask nicely I bet @c-schwarze could write some code to do it.

I didn't realize we had so many in Cascade already.

**Comment by annmarieven** [comment]
haha pretty please @c-schwarze ? : )

**Comment by kelslundberg** [comment]
yes! please, @c-schwarze ?! :) :)

**Comment by c-schwarze** [comment]
Working on it. :)

**Comment by c-schwarze** [comment]
Done. I believe I got them all.
