### ISSUE TITLE
Create a redirect for all unpublished job postings

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/tinker#43]
We need a system for creating redirects every time a job is unpublished. This is what was discussed today between @e-jameson, @kelslundberg, and I:

email to webmaster@bethel.edu
use the cascade url/id from the 'view the asset' link
point them to one page within employment (something that says, hey - this job has been filled...)
webmaster looks at email subject to know when to apply this rule

@vedmic has said this is low priority and can be looked at after we launch responsive.

**Comment by c-schwarze** [comment]
is this email currently being sent on a job posting unpublish?

**Comment by annmarieven** [comment]
Yes.

**Comment by c-schwarze** [comment]
I have tried to unpublish a job posting, but no email gets sent to webmaster@bethel.edu...

**Comment by e-jameson** [comment]
@c-varberg can you look into this more. Let Caleb or myself know if you need help setting up a local copy of Tinker.

**Comment by c-varberg** [comment]
Hey @annmarieven, I am only seeing two workflows for job postings, 'Archive Job Posting', and 'Publish Job Posting'. Does Archive Job Postings also get called when job postings are unpublished? I don't understand workflows very well, so it may just be I'm looking in the wrong spot haha.

**Comment by annmarieven** [comment]
The 'Archive Job Posting' workflow automatically unpublishes the job as well. Is that your question?

**Comment by c-varberg** [comment]
@annmarieven I was wondering what workflow is run when a job is unpublished?

**Comment by annmarieven** [comment]
oops. just saw this. this workflow is what unpublishes jobs: https://cms.bethel.edu/entity/open.act?id=a2d5035f8c5865137eca47069e02533e&type=workflowdefinition

**Comment by c-schwarze** [comment]
@e-jameson I think this can be removed, as we have the new HR job app thing. Right?
