### ISSUE TITLE
Auto Delete and Redirect

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#45]
@e-jameson, we've set up a workflow for sites that don't need approvals. This workflow will automatically delete pages for these users and we want them to redirect to bethel.edu. This is for SEO purposes more than anything else.

I've sent a test through so there should be an email in webmaster@bethel.edu with the workflow information.

We need to take the url from the 'view the asset' link and redirect that to bethel.edu.

Here is the workflow in case you need it: https://cms.bethel.edu/entity/open.act?id=73bee9ab8c5865132a1de4ef90540b46&type=workflowdefinition

Let me know if you need anything else from me!

**Comment by c-schwarze** [comment]
I create a page named "basic" within my test folder, where my test folder had the workflow attached.

The email that Cascade gives only contains this snippet of information to create the redirect:
"(Auto Delete and Redirect: basic)".

So this workflow will need to be applied to the global folder, or else we need to have some way to find the page within the file structure. Can we just put the workflow on the global folder? Or will that mess things up?

Let me know if that doesn't make sense.

**Comment by annmarieven** [comment]
We can't put it at the global folder, unfortunately. I thought the email would contain more information. Can you forward me the email that webmaster got?

**Comment by e-jameson** [comment]
The email did have a link to the asset, but the asset is already deleted by the time it sends the email so you can't look up the page info via the Cascade ID. The link doesn't even work in the browser

**Comment by annmarieven** [comment]
hmmm.... we'll have to look into this a little more after responsive.

**Comment by annmarieven** [comment]
We'll just have their deletions go through an "approval" workflow for now so we can put in a redirect for them.
