### ISSUE TITLE
Job Posting auto redirect when archived

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#46]
@e-jameson, we've set up a workflow for the employment site to unpublish old job postings.

We need to take the url from the 'view the asset' link and redirect that to a page @kelslundberg will provide.

Here is the workflow in case you need it: https://cms.bethel.edu/entity/open.act?id=4fabbd3f8c5865131faa2077a536cfd5&type=workflowdefinition

Let me know if you need anything else from me!

**Comment by kelslundberg** [comment]
Here's a page:

https://cms.bethel.edu/entity/open.act?id=c6566b328c5865132a1de4efa2836f11&type=page

What do you think? It hasn't been published yet.

**Comment by annmarieven** [comment]
Awesome! @e-jameson can you take care of this?

**Comment by c-schwarze** [comment]
This is working. Any job posting that expires will automatically trigger tinker to create a redirect to Kelsey's page. It should take about 5 minutes from the expiration to have the redirect created.
