### ISSUE TITLE
Adding adult program metadata to events

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/Tinker#47]
Looks like we have metadata fields already created for GS and CAPS programs, but they're not in Tinker.

https://cms.bethel.edu/entity/open.act?id=1a525c038c5865135b5a2d9efa247727&type=metadataset

I do need to add seminary programs. I'll do that now. Then we can add the adult program metadata to Tinker.

**Comment by kelslundberg** [comment]
Okay sem programs should be there now too!

**Comment by annmarieven** [comment]
I need to contact the event loaders to let them know. Reopening.

**Comment by annmarieven** [comment]
Done. Closing.
