### ISSUE TITLE
Event Submission Updates

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#48]
This is a request for 3 things.

- [x] allow career-development-calling events to go into the main 'events/year' folder. we no longer want a subfolder for these events.
- [x] add a rule for events tagged as chapel to go into a 'chapel' folder
- [x] add a rule for events tagged as ANY admissions office to go into an 'admissions' folder

Let me know if you need any more information from me!

**Comment by c-schwarze** [comment]
For the 2nd and 3rd rules, do the 'chapel' and 'admissions' folders go in the year? 

/events/2015/chapel/

or /events/chapel/

**Comment by annmarieven** [comment]
They'll be in the year folders.

**Comment by c-schwarze** [comment]
Are we going to want these folders to be created automatically?

**Comment by annmarieven** [comment]
Can we do that? That would be awesome. Otherwise Brooke has to manually build them out every year.

**Comment by c-schwarze** [comment]
Tinker will create the folder for a submitted event, if the folder does not exist.

Also, the other 3 requests have been completed and tested.

**Comment by c-schwarze** [comment]
When tinker creates folders for events, they will have the metadata:

Skip-in-breadcrumb = "Yes"

Reopen if there are any issues
