### ISSUE TITLE
Tinker faculty confirmation page

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#49]
FOR NEW BIOS - can we change it to:
Congrats!
You've successfully submitted your faculty bio. If you have any questions, feel free to contact your web author.
Thanks for creating your bio!

FOR EDITED BIOS - can we change it to:
You've successfully edited your faculty bio. If you have any questions, feel free to contact your web author. 
Thanks for keeping your bio up to date!

**Comment by c-schwarze** [comment]
Updated and live.
