### ISSUE TITLE
Events list preview showing incorrect date/time

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/Tinker#51]
@e-jameson,

Brooke sent in this job:
"In Tinker on the events page under Your Events the preview data of date and time for the event is not right, possibly a time zone difference? I have had a few people mention this to me and I just checked my account to confirm it. For example, one of my events has an event date of August 18, 2014 6-8 pm, but the preview data shows Aug 1, 11 pm - Aug 2, 1 am."

Would you look into why this is happening?

**Comment by a-gundy** [comment]
Footprints job 13871.

**Comment by c-schwarze** [comment]
I just updated the Events homepage date format.
