### ISSUE TITLE
Buy Tickets button

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#52]
There is a field on the Tinker form that says "Select a heading for the registration section"

If they choose 'ticketing' can the button say "Buy tickets" instead of "Register"

Let me know if you need any more info.

Thanks!

**Comment by c-schwarze** [comment]
I updated cascade's format so now selecting "Ticketing" and providing a wufoo code, will display a "Buy Tickets" button. 

Let me know if you need anything else.

**Comment by annmarieven** [comment]
Awesome! Thank you!!!
