### ISSUE TITLE
Faculty category fields

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#54]
Can we add a radio button at the bottom of the faculty bio form (before the categories) that says, "I need to change my school and programs that I teach."

By default it should be set to 'no' but if they choose yes, all the category fields should appear.

Let me know if you need more info from me!

**Comment by c-schwarze** [comment]
This is updated and live. Let me know if you need any modifications to that.

**Comment by annmarieven** [comment]
Beautiful! Thank you!!
