### ISSUE TITLE
Show site nav metadata 

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/Tinker#55]
@c-schwarze, can you have Tinker set the "hide-site-nav" metadata option to "Hide" for both Events Faculty Bios, as well as go through and set existing Events/Bios as well? 

Let me know if you have any questions

**Comment by c-schwarze** [comment]
I couldn't find any events that didn't already have the option set to "Hide", so I didn't mess with that. I can do more extensive checking, or if you know of one, that would be helpful.

All Faculty Bios are now set to "Hide".

All future Events/Faculty Bios will be set to "Hide"

**Comment by annmarieven** [comment]
I just want to make sure that events using the content type 'event with nav' are not hiding site navigation. Events that are in performing and visual arts use this content type. 

content type:
https://cms.bethel.edu/entity/open.act?id=6a291d568c5865132786f4d038aa2295&type=contenttype&

page example:
https://www.bethel.edu/events/arts/music/2015/hong-wang-cello--herbert-johnson-piano

**Comment by c-schwarze** [comment]
Oops. Fixed now. 

Events no nav:     "hide-from-nav" = "Hide"

Events with nav:    "hide-from-nav" = "Do not hide"

**Comment by c-schwarze** [comment]
Changed the wrong metadata field. 

It now sets "hide-site-nav" instead of "hide-from-nav"

**Comment by c-schwarze** [comment]
Events only have the metadata "hide-from-nav". They do now have "hide-site-nav". Is this something we would like to add?

https://cms.bethel.edu/entity/open.act?id=1a525c038c5865135b5a2d9efa247727&type=metadataset&

**Comment by c-schwarze** [comment]
Jake, the Event No Nav and Event With Nav take care of the site navigation being hidden/shown. This is being done at the configuration set level.

Should be working fine. Let me know if anything needs to change.
