### ISSUE TITLE
New event category

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#56]
I added a new event category to the metadata for events. It doesn't look like it's automatically showing up so that's why I'm creating a github :)

https://cms.bethel.edu/entity/open.act?id=1a525c038c5865135b5a2d9efa247727&type=metadataset
In the offices field, I added "Admissions - Undergrad Off-Campus"

**Comment by c-schwarze** [comment]
I'm not seeing it in the Events metadata...?

https://cms.bethel.edu/entity/edit.act?id=1a525c038c5865135b5a2d9efa247727&type=metadataset

**Comment by annmarieven** [comment]
hm. well that's a bigger problem then. I added it the first time and it said my edit was successful. But, clearly it's not there...  :) So I just tried AGAIN and it said it was successful but after going back in, it's still not there. :sob:

**Comment by c-schwarze** [comment]
Hmm. Its happening to me too. :( I don't know whats going on with that. No changes are working.

Also, I see "Admissions - Undergrad Off-Campus Undergraduate" which seems redundant and the same option? should we just change the name of that?

**Comment by c-schwarze** [comment]
Try using the advanced editor instead of using the text fields/buttons.

**Comment by annmarieven** [comment]
Ok, that worked. Weird. Thanks for your help :)
