### ISSUE TITLE
Event page edits

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#57]
From FP job 14230.

When someone makes an edit to an event in Tinker, can the button to edit it again take them to a page that says 'Your edits are pending approval. Please wait until they have been approved before you make additional edits.'

If that doesn't work, another option is to have the edit button update to say "Edits pending approval" and not be clickable.

**Comment by c-schwarze** [comment]
Updated. If you try to edit an event in a workflow, it will redirect you to https://tinker.bethel.edu/event/in-workflow

Let me know if the text or how this is done should be modified. I can try out the second option, however someone with many events (like a chapel event manager) could slow things down.

**Comment by e-jameson** [comment]
Assigning to @annmarieven to reply to case 14230.

**Comment by annmarieven** [comment]
Responded to Brooke.
