### ISSUE TITLE
Event content type

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#59]
We would like to combine our 'event no nav' and 'event with nav' content types.

Since we have the nav option in the metadata now, I would like to change 'event no nav' to just be called "Event".

I would also like Tinker to know, based on the categories selected, which events should hide navigation or not in the metadata.

Can we do this?

**Comment by c-schwarze** [comment]
Yep! I'll get that done tomorrow

**Comment by annmarieven** [comment]
let me know when it's done so I can run some tests through and then combine the content types :) danke!!!

**Comment by c-schwarze** [comment]
Okay, all events submitted through Tinker will use "event" metadata instead of the "event no nav" or "event with nav".

Already created events should have the "event" metadata. Let me know if you find any that are broken.
