### ISSUE TITLE
Faculty bio school and program fields

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#63]
Right now the school and program fields are 'hidden' behind a field that asks this question:

I need to change my school and programs that I teach.
Yes  No 

---
This is good for bios that are just being edited. However, for people submitting NEW bios, the question doesn't make that much sense. They think nothing has 'changed' for them, so they don't click yes to expand it and select the school/programs that they teach. 

Can we make these fields appear for NEW bios? And then hide (the way we do it now) for existing ones?

**Comment by c-schwarze** [comment]
Updated. Let me know if it works how you want it.

**Comment by e-jameson** [comment]
Looks good.
