### ISSUE TITLE
Verify username

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/Tinker#64]
@c-schwarze can you write a custom validator to verify the username entered in the Faculty Bio create or edit form is a correct username? 

http://wtforms.simplecodes.com/docs/0.6/validators.html

You can make an API call with the value and check the result set. {} means it is invalid.

wsapi.bethel.edu/username/<username>/roles

Username is behind auth: https://confluence.bethel.edu/display/WebSrv/Auth.

**Comment by c-schwarze** [comment]
Usernames entered will be validated.
