### ISSUE TITLE
Tinker faculty bio changes

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#66]
## CAS
**New bio**
Confirmation message - tinker.bethel.edu/faculty-bios/confirm-new

- [x] CHANGE TO - "Congrats! You've successfully created a new bio. Since it's a brand new bio, it's been sent for approval but will be ready to view in 2-3 business days. Thanks for creating your bio!"

**Existing bio**
- [x] Bio will auto-publish and trigger the 2 publish sets (Faculty Bio XML, Faculty Listings Undergrad) -- IS TINKER DOING THIS?

## CAPS/GS
**New bio**
Use same confirmation page as CAS.

## Seminary
- [ ] Confirmation message - We need to see what we're doing with sem bios. If new bios aren't going through a workflow, the existing confirmation message won't work.
- [x] Bio will auto-publish and trigger the two publish sets (Faculty Bio XML, Faculty Listings Sem) -- IS TINKER DOING THIS?

----
Edit bio in workflow - https://tinker.bethel.edu/faculty-bios/in-workflow
- [x] CHANGE TO -
Title - "Pending Approval"
Heading - "Edits Pending Approval"
Body - "You recently made edits to your bio and are currently pending approval. Please wait until the changes have been approved before you make additional edits. Go back to your faculty bios."

**Comment by annmarieven** [comment]
I got this message when I edited a caps/gs bio:
https://tinker.bethel.edu/faculty-bios/submit
Congrats!
You've successfully edited your faculty bio. If you have any questions, feel free to contact your web author. 
Your bio is currently in a workflow


Thanks for keeping your bio up to date!

----
Can you tell me which schools show that message?

**Comment by c-schwarze** [comment]
Any edited bio will display that message. Except the "Your bio is currently in a workflow" portion. That will only display when the bio is in a workflow. Which is caps/gs edits.

**Comment by annmarieven** [comment]
hm.. that seems confusing.

Can we have caps/gs bios say:
"Congrats!
You've successfully edited your bio. You changes have been sent for approval but will be ready to view in 2-3 business days. 

Thanks for keeping your bio up to date!"

CAS bios can say:
"Congrats!
You've successfully edited your faculty bio. If you have any questions, feel free to contact your web author. 

Thanks for keeping your bio up to date!"

**Comment by c-schwarze** [comment]
What about seminary bios?

**Comment by annmarieven** [comment]
Ugh. We still don't know what we're doing for Seminary bios. :-P

Let's have them all auto-approve for now and show cas messages. Can we bring this up in our meeting on Thursday?

**Comment by hamtim** [comment]
This came up at the catalog meeting yesterday. All 3 schools would like
their bios to be approved (knowing this is a change for CAS). We are
waiting on the deans to indicate if there are any additional fields
required for the catalog and to indicate who will be the approver.


----------
Timothy Hammer
Senior Strategist
Web & Creative Services

Bethel University
3900 Bethel Drive
St. Paul, MN 55112
o: 651.638.6784 c: 515.971.5659

**Comment by annmarieven** [comment]
tinker.bethel.edu/faculty-bios/confirm-new

CHANGE TO - "Congrats! You've successfully created a new bio. Your brand new bio has been sent for approval but will be ready to view in 2-3 business days. Thanks for creating your bio!"

https://tinker.bethel.edu/faculty-bios/confirm-edit
CHANGE TO - "Congrats! You've successfully edited your bio. Your edits have been sent for approval but will be ready to view in 2-3 business days. Thanks for keeping your bio up to date.

If you have any questions, you can contact Lauren Pareigat (CAS) or Annette Abel (CAPS/GS)."

**Comment by c-schwarze** [comment]
updated confirmation texts

**Comment by annmarieven** [comment]
3 minor adjustments.

https://tinker.bethel.edu/faculty-bio/confirm-new
Can there be a little spacing (like on our site between p tags) between the paragraphs?

https://tinker.bethel.edu/faculty-bio/confirm-edit
Move "Thanks for keeping your bio up to date!" to the first paragraph.
Can there be a little spacing (like on our site between p tags) between the paragraphs?
Adjust last sentence to "If you have any questions, you can contact Lauren Pareigat (CAS), Annette Abel (CAPS/GS), or Jenny Vang (Seminary).

**Comment by c-schwarze** [comment]
Updated those 3 requests.
