### ISSUE TITLE
Event photo disappears

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#67]
From Jan Jessup in job 14953:
Whenever a Tinker user submits an edit to a page to which I've attached a photo, approving the submission reverts to the no-photo original submission. Any work-around for that?

**Comment by c-schwarze** [comment]
Tinker is doing its job fine. However, if Jan edits a bio and does not publish the Faculty Bio xml, then the bug stated above occurs.

Do we currently have workflows for faculty bios that publish the Faculty Bio xml?

**Comment by annmarieven** [comment]
This is about events, not faculty bios :)

**Comment by c-schwarze** [comment]
Oh...awkward. My bad.

**Comment by c-schwarze** [comment]
This should be fixed now.
