### ISSUE TITLE
CAS Faculty Bio Process

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#69]
What needs to happen to make the CAS faculty bio process be almost identical to CAPS/GS? 

They will have different workflows but the process will be the same (they have to go through approvals) for new and editing existing bios.

I can update this document if you want me to if it will help facilitate the change - https://docs.google.com/document/d/1pC5kkm3IhQqpGIcFj-LKXsn2s3BchP8r8SMquFxCw3Y/edit

Let me know!

**Comment by c-schwarze** [comment]
Just send me the new/updated workflow for CAS bios and I will update Tinker.

**Comment by annmarieven** [comment]
updated CAS workflow: https://cms.bethel.edu/entity/open.act?id=f1638f598c58651313b6fe6b5ed835c5&type=workflowdefinition

I am also working on updating the google doc I referred to.

**Comment by annmarieven** [comment]
Here's the updated document with the correct process:
https://docs.google.com/document/d/1pC5kkm3IhQqpGIcFj-LKXsn2s3BchP8r8SMquFxCw3Y/edit#heading=h.uzkrd948ui4e

Please make sure Tinker is setup this way and let me know if you have any questions :)
Thanks!

**Comment by c-schwarze** [comment]
CAS should now act the same way as CAPS/GS bios
