### ISSUE TITLE
Duplicate Tinker Events

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#70]
Is there a way we can have a duplicate button for events? Next to view, edit, delete.

It would duplicate the information and bring them to the edit screen to make any minor tweaks. Then the event would get submitted for approval like a new event.

Let me know if you need more info about this request.

**Comment by c-schwarze** [comment]
Updated. The new "duplicated" event will be treated as a new event for all workflow purposes.

**Comment by annmarieven** [comment]
Looks good!
