### ISSUE TITLE
Faculty bio username checker

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#71]
This person is trying to submit their bio but keeps getting an error.  They just emailed all seminary faculty so can we get this figured out asap?

---------- Forwarded message ----------
From: *Mark Strauss* <m-strauss@bethel.edu>
Date: Thursday, July 2, 2015
Subject: Action Required for Faculty Bios--due July 13
To: Laura Harville <laura-harville@bethel.edu>

Hi Laura,

I don't know what's wrong with this page, but it keeps sending me error
messages when I try to create a profile. It say "invalid user name" but
doesn't say why.

Mark

Mark L. Strauss, Ph.D.
University Professor of New Testament
Bethel Seminary San Diego
6116 Arosa St.
San Diego, CA 92115

Work 619 325-5221
Mobile 619 987-3041
m-strauss@bethel.edu

**Comment by annmarieven** [comment]
Remind me.... was the username field being auto populated or something they are entering themselves?

**Comment by c-schwarze** [comment]
It is something autopopulated if they already have created one. It is then checking to see if the username comes up in...banner? 

Do we know his username? That would make this an easy test.

**Comment by annmarieven** [comment]
If he's creating a brand new one, does he have to enter it himself?

**Comment by c-schwarze** [comment]
Yes

**Comment by annmarieven** [comment]
Ah, probably just user error then. mstrauss is the username.

**Comment by e-jameson** [comment]
Is there a more helpful message we can put there. Maybe like "Enter your BCA username"?

**Comment by annmarieven** [comment]
Let's just do "Enter your Bethel username." I don't think people know what BCA is.. :)
