### ISSUE TITLE
Broken link on tinker.bethel.edu

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#75]
The faculty bio link on tinker.bethel.edu is broken. (not the top one but the one with the graphic)

Can we also put in a redirect? Cause it looks like people have the broken url (ending in /faculty-bios/ instead of just /faculty-bio/)

**Comment by c-schwarze** [comment]
Oops. Fixed the link. Do we need to add a redirect if the link is fixed?

**Comment by annmarieven** [comment]
Yes. People have the old url. Thanks!

**Comment by c-schwarze** [comment]
No problem! Added redirect.
