### ISSUE TITLE
Faculty Bio Issues/Questions

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#77]
I was watching an admin use Tinker and we ran across a couple of issues/questions.

- [x] job title fields broken
- [x] job title fields required
- [x] usernames
- [ ] new bio button for admin

On some bios, all of the job title fields are expanded and you can't select anything. I also noticed there is a '-select-' option but it doesn't appear as the first, default item in the drop down. Can it? And can it be a lowercase s? https://tinker.bethel.edu/faculty-bio/edit/b4b5aec88c5865132467e6ffe322d2f3 

I noticed someone had chosen a school but no program, can we make the program fields required?
https://tinker.bethel.edu/faculty-bio/edit/ada745128c58651314811f9cf403ee48#page-title If I do this in Cascade will it carry over to Tinker?

We came across a bio without a username. I'm wondering if we can get a report of all bios without an empty username field. And how was it not entered if it's required? https://tinker.bethel.edu/faculty-bio/edit/ad699cc98c5865133a5d3f89a4d9b73a#page-title

The new bio button disappears if there is a bio already in the list for any given person. Can the button stay there for someone who is in the Cascade group for that specific department? That way admin can continue to add bios for people. Can it be there for any user in the Tinker Faculty Bios group as well?

**Comment by c-schwarze** [comment]
I think that we made the username field required after these were submitted. All bios should have to have the username field filled out. Here is the list of faculty bios that have no username (author field):

/academics/faculty/robey-nathan
/academics/faculty/stoeckman-angela
/academics/faculty/shypulski-eydie
/academics/faculty/lancaster-steven
/academics/faculty/eaton-alex
/academics/faculty/dikkers-seann
/academics/faculty/suave-shawn
/academics/faculty/mcneel-sandie
/academics/faculty/anderson-mark
/academics/faculty/vintinner-ishaa
/academics/faculty/plazaruiz-cristina
/academics/faculty/maltese-preciado-gina
/academics/faculty/lindberg-mark
/academics/faculty/butler-anna
/academics/faculty/bougie-bonnie
/academics/faculty/adams-leighanne
/academics/faculty/kinney-bill

**Comment by annmarieven** [comment]
@ale73233 can you look up the bios caleb included above? we need to enter usernames into the 'author' field. 

In order to find the usernames, go to footprints and open a new job, enter the first and last name into the contact information section and hit enter. this will automatically fill in the username field which you can then copy and paste into the user's bio.

BEFORE you publish them to production, you need to also do the faculty bio job title change on these like we've done with the other ones. if they have multiple jobs and multiple schools selected in the metadata, then we can't make the job title switch and can't publish them to production.

**Comment by ale73233** [comment]
I entered all of the usernames and published them to prod.

**Comment by c-schwarze** [comment]
@e-jameson could you take a look at this? We just need to add the new bio button for admin
