### ISSUE TITLE
Tinker Metadata Sync

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/Tinker#78]
Can we add locations to this?
https://github.com/betheluniversity/Tinker/blob/master/tinker/sync/metadata.py

Here are the locations:
https://cms.bethel.edu/entity/open.act?id=98476db08c586513091377e50bd6ef0a&type=structureddatadefinition&

**Comment by annmarieven** [comment]
The other place it should be synced is here: https://cms.bethel.edu/entity/open.act?id=703ebc8d8c5865132395524d89bfaeb9&type=structureddatadefinition&

Thanks!

**Comment by c-schwarze** [comment]
Done.
