### ISSUE TITLE
Cache-test rename :)

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/tinker#94]
We would like to request that the cache-test be renamed to cache-clear. Thanks much!

Also, why is the Tinker repository capitalized? ;)

**Comment by emily-johnson** [comment]
@annmarieven says that would be awesome!

**Comment by c-schwarze** [comment]
That sounds good to me. @nate-li can do this while he is doing the admin blueprint move.

**Comment by e-jameson** [comment]
@emily-johnson do you speak on behalf of @annmarieven now? :) 

I updated the URL to be cache-clear.

**Comment by emily-johnson** [comment]
Haha that has happened a lot today.. she just makes me do her dirty work ;)

Thanks!

**Comment by annmarieven** [comment]
Isn't that what students are for?? .... jk! :stuck_out_tongue_winking_eye:

**Comment by c-schwarze** [comment]
@nate-li when you get a chance, could you add an interface for this? (as per Eric's comment above)

**Comment by nate-li** [comment]
Will do!

**Comment by c-schwarze** [comment]
Closing
